# Generated by Django 5.0.6 on 2024-07-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Firstapp',
        ),
    ]
